// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace nkay_fabs_backend.Migrations
{
    [DbContext(typeof(FabricsDbContext))]
    [Migration("20260515112702_AddAuthOrdersNotificationsMessages")]
    partial class AddAuthOrdersNotificationsMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nkay_fabs_backend.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(2762),
                            Description = "A vibrant wax print fabric widely used across Nigeria, known for its bold, colorful patterns and commonly worn at celebrations, ceremonies and everyday occasions.",
                            Name = "Ankara",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(2788)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8795),
                            Description = "A hand-loomed Yoruba fabric from South-Western Nigeria, traditionally worn at weddings and ceremonies, available in three types: Oja, Ipele, and Fila.",
                            Name = "Aso-Oke",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8820)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8837),
                            Description = "A traditional Yoruba indigo-dyed fabric from Nigeria, featuring intricate tie-dye or starch-resist (eleko) patterns, originating from Abeokuta and Ibadan.",
                            Name = "Adire",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8839)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8842),
                            Description = "A luxurious fabric popular in South-Eastern Nigeria, commonly worn by Igbo and Ijaw women during weddings and special ceremonies, often adorned with glitter or embroidery.",
                            Name = "George Fabric",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8843)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8846),
                            Description = "A traditional Igbo fabric from South-Eastern Nigeria featuring lion head prints, typically worn by men of title and distinction during cultural events and ceremonies.",
                            Name = "Isiagu",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8847)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8850),
                            Description = "A hand-woven textile from Akwete town in Abia State, Nigeria, produced by Igbo women and known for its unique weaving techniques and complex patterns.",
                            Name = "Akwete",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8852)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8854),
                            Description = "A richly embroidered fabric from Northern Nigeria, featuring intricate hand-stitched patterns around the neckline and chest, commonly used in traditional Hausa and Fulani attire.",
                            Name = "Hausa Embroidered Fabric",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8856)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8859),
                            Description = "A coarse, hand-woven cotton fabric from Northern Nigeria traditionally produced by the Hausa people, known for its natural earthy tones and used in everyday traditional wear.",
                            Name = "Kijipa",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8860)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8863),
                            Description = "A plain hand-woven Yoruba cloth from South-Western Nigeria, typically woven in white or neutral tones and used as a base fabric for dyeing techniques like Adire.",
                            Name = "Ofi",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8864)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8867),
                            Description = "A dark navy blue hand-woven Yoruba fabric from South-Western Nigeria, traditionally reserved for elders and people of high social standing during important ceremonies.",
                            Name = "Etu",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8869)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8871),
                            Description = "A prestigious hand-woven Yoruba fabric made from the silk of the Anaphe moth, featuring a distinctive brown or beige tone and traditionally worn by Yoruba royalty.",
                            Name = "Sanyan",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8873)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8875),
                            Description = "A fine hand-woven fabric from the Yoruba people of South-Western Nigeria, known for its delicate thread work and typically worn during high-profile traditional occasions.",
                            Name = "Alabere",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8877)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8880),
                            Description = "A traditional hand-woven fabric from Okene in Kogi State, produced by the Ebira people, known for its bold geometric patterns and cultural significance in Central Nigeria.",
                            Name = "Okene Weave",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8881)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8884),
                            Description = "A traditional handwoven fabric from the Ogoja people of Cross River State, known for its earthy tones and symbolic patterns used in ceremonial and ritual contexts.",
                            Name = "Ogoja Cloth",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8885)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8888),
                            Description = "A traditional fabric from the Urhobo people of Delta State, Nigeria, featuring distinct woven patterns and used during cultural festivals and important ceremonies.",
                            Name = "Urhobo Cloth",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8889)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8892),
                            Description = "A hand-woven fabric from the Igala people of Kogi State, Nigeria, known for its colorful striped patterns and cultural importance in royal and ceremonial dressing.",
                            Name = "Igala Weave",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8894)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8896),
                            Description = "A traditional hand-woven fabric from the Tiv people of Benue State, Nigeria, distinctively featuring black and white striped patterns called Anger, used in traditional ceremonies.",
                            Name = "Tiv Cloth",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8898)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8900),
                            Description = "A traditional fabric from the Nupe people of Niger State, Nigeria, known for intricate hand-loom weaving techniques and vibrant colors used in royal ceremonial attire.",
                            Name = "Nupe Weave",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8902)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8904),
                            Description = "A traditional fabric from the Efik people of Cross River State, Nigeria, commonly used during the famous Calabar carnival and cultural ceremonies such as the Ekpe festival.",
                            Name = "Efik Cloth",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8906)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8909),
                            Description = "A traditional ceremonial fabric from the Ijaw people of the Niger Delta region, typically featuring bold colors and worn alongside coral beads during important cultural and royal events.",
                            Name = "Ijaw Wrapper",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 72, DateTimeKind.Unspecified).AddTicks(8910)
                        });
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 26, 59, 906, DateTimeKind.Unspecified).AddTicks(2255),
                            HexCode = "#000000",
                            Name = "Black",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(5186)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7559),
                            HexCode = "#FFFFFF",
                            Name = "White",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7567)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7574),
                            HexCode = "#FF0000",
                            Name = "Red",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7575)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7577),
                            HexCode = "#001F5B",
                            Name = "Navy Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7578)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7580),
                            HexCode = "#4169E1",
                            Name = "Royal Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7580)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7582),
                            HexCode = "#87CEEB",
                            Name = "Sky Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7583)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7585),
                            HexCode = "#008080",
                            Name = "Teal",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7585)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7587),
                            HexCode = "#40E0D0",
                            Name = "Turquoise",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7588)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7590),
                            HexCode = "#008000",
                            Name = "Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7590)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7592),
                            HexCode = "#6B8E23",
                            Name = "Olive Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7593)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7595),
                            HexCode = "#98FF98",
                            Name = "Mint Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7595)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7597),
                            HexCode = "#32CD32",
                            Name = "Lime Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7598)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7600),
                            HexCode = "#FFFF00",
                            Name = "Yellow",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7600)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7602),
                            HexCode = "#FFDB58",
                            Name = "Mustard Yellow",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7603)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7604),
                            HexCode = "#FFD700",
                            Name = "Gold",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7605)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7607),
                            HexCode = "#FF8C00",
                            Name = "Orange",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7607)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7609),
                            HexCode = "#FF6B6B",
                            Name = "Coral",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7610)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7611),
                            HexCode = "#FFCBA4",
                            Name = "Peach",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7612)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7614),
                            HexCode = "#FFC0CB",
                            Name = "Pink",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7615)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7616),
                            HexCode = "#FF69B4",
                            Name = "Hot Pink",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7617)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7619),
                            HexCode = "#FF00FF",
                            Name = "Fuchsia",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7620)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7660),
                            HexCode = "#FF0090",
                            Name = "Magenta",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7660)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7662),
                            HexCode = "#800080",
                            Name = "Purple",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7663)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7665),
                            HexCode = "#E6E6FA",
                            Name = "Lavender",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7666)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7667),
                            HexCode = "#EE82EE",
                            Name = "Violet",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7668)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7670),
                            HexCode = "#4B0082",
                            Name = "Indigo",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7670)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7672),
                            HexCode = "#800000",
                            Name = "Maroon",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7673)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7674),
                            HexCode = "#800020",
                            Name = "Burgundy",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7675)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7677),
                            HexCode = "#722F37",
                            Name = "Wine Red",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7678)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7679),
                            HexCode = "#DC143C",
                            Name = "Crimson",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7680)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7682),
                            HexCode = "#FF2400",
                            Name = "Scarlet",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7683)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7684),
                            HexCode = "#8B4513",
                            Name = "Brown",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7685)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7687),
                            HexCode = "#7B3F00",
                            Name = "Chocolate",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7688)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7689),
                            HexCode = "#C68642",
                            Name = "Caramel",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7690)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7691),
                            HexCode = "#D2B48C",
                            Name = "Tan",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7692)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7694),
                            HexCode = "#F5F5DC",
                            Name = "Beige",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7695)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7696),
                            HexCode = "#FFFDD0",
                            Name = "Cream",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7697)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7699),
                            HexCode = "#FFFFF0",
                            Name = "Ivory",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7699)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7701),
                            HexCode = "#FAF9F6",
                            Name = "Off White",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7702)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7703),
                            HexCode = "#D3D3D3",
                            Name = "Light Gray",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7704)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7706),
                            HexCode = "#808080",
                            Name = "Gray",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7707)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7708),
                            HexCode = "#404040",
                            Name = "Dark Gray",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7709)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7711),
                            HexCode = "#36454F",
                            Name = "Charcoal",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7711)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7713),
                            HexCode = "#C0C0C0",
                            Name = "Silver",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7714)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7715),
                            HexCode = "#B76E79",
                            Name = "Rose Gold",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7716)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7718),
                            HexCode = "#B87333",
                            Name = "Copper",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7718)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7720),
                            HexCode = "#CD7F32",
                            Name = "Bronze",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7721)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7722),
                            HexCode = "#C3B091",
                            Name = "Khaki",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7723)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7725),
                            HexCode = "#C2B280",
                            Name = "Sand",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7726)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7727),
                            HexCode = "#B7410E",
                            Name = "Rust",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7728)
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7729),
                            HexCode = "#FA8072",
                            Name = "Salmon",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7730)
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7732),
                            HexCode = "#DCAE96",
                            Name = "Dusty Rose",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7733)
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7759),
                            HexCode = "#DE5D83",
                            Name = "Blush",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7760)
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7762),
                            HexCode = "#89CFF0",
                            Name = "Baby Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7762)
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7764),
                            HexCode = "#B0E0E6",
                            Name = "Powder Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7765)
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7766),
                            HexCode = "#007BA7",
                            Name = "Cerulean",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7767)
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7769),
                            HexCode = "#0047AB",
                            Name = "Cobalt Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7770)
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7771),
                            HexCode = "#B2AC88",
                            Name = "Sage Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7772)
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7774),
                            HexCode = "#228B22",
                            Name = "Forest Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7775)
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7776),
                            HexCode = "#50C878",
                            Name = "Emerald Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7777)
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7779),
                            HexCode = "#00A86B",
                            Name = "Jade",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7779)
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7781),
                            HexCode = "#C8A2C8",
                            Name = "Lilac",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7782)
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7784),
                            HexCode = "#E0B0FF",
                            Name = "Mauve",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7784)
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7786),
                            HexCode = "#DDA0DD",
                            Name = "Plum",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7787)
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7789),
                            HexCode = "#614051",
                            Name = "Eggplant",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7789)
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7791),
                            HexCode = "#FFF44F",
                            Name = "Lemon Yellow",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7792)
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7793),
                            HexCode = "#FFBF00",
                            Name = "Amber",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7794)
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7796),
                            HexCode = "#FBCEB1",
                            Name = "Apricot",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7797)
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7798),
                            HexCode = "#E2725B",
                            Name = "Terracotta",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7799)
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7801),
                            HexCode = "#CB4154",
                            Name = "Brick Red",
                            UpdatedAt = new DateTime(2026, 5, 15, 12, 27, 0, 70, DateTimeKind.Unspecified).AddTicks(7801)
                        });
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Fabric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerYard")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockYards")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColorId");

                    b.ToTable("Fabrics");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FabricId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FabricId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Conversation", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nkay_fabs_backend.Entities.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.EmailVerification", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.User", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Fabric", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.Category", "Category")
                        .WithMany("Fabrics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nkay_fabs_backend.Entities.Color", "Color")
                        .WithMany("Fabrics")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Message", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nkay_fabs_backend.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Notification", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Order", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.OrderItem", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.Fabric", "Fabric")
                        .WithMany()
                        .HasForeignKey("FabricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nkay_fabs_backend.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabric");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.OtpVerification", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.User", "User")
                        .WithMany("OtpVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Category", b =>
                {
                    b.Navigation("Fabrics");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Color", b =>
                {
                    b.Navigation("Fabrics");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.User", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("EmailVerifications");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("OtpVerifications");
                });
#pragma warning restore 612, 618
        }
    }
}
