// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace nkay_fabs_backend.Migrations
{
    [DbContext(typeof(FabricsDbContext))]
    [Migration("20260515132406_AddedUpdatedAtToEmailVerificationTable")]
    partial class AddedUpdatedAtToEmailVerificationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nkay_fabs_backend.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(5627),
                            Description = "A vibrant wax print fabric widely used across Nigeria, known for its bold, colorful patterns and commonly worn at celebrations, ceremonies and everyday occasions.",
                            Name = "Ankara",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(5658)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8678),
                            Description = "A hand-loomed Yoruba fabric from South-Western Nigeria, traditionally worn at weddings and ceremonies, available in three types: Oja, Ipele, and Fila.",
                            Name = "Aso-Oke",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8692)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8704),
                            Description = "A traditional Yoruba indigo-dyed fabric from Nigeria, featuring intricate tie-dye or starch-resist (eleko) patterns, originating from Abeokuta and Ibadan.",
                            Name = "Adire",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8709)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8717),
                            Description = "A luxurious fabric popular in South-Eastern Nigeria, commonly worn by Igbo and Ijaw women during weddings and special ceremonies, often adorned with glitter or embroidery.",
                            Name = "George Fabric",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8722)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8729),
                            Description = "A traditional Igbo fabric from South-Eastern Nigeria featuring lion head prints, typically worn by men of title and distinction during cultural events and ceremonies.",
                            Name = "Isiagu",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8734)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8742),
                            Description = "A hand-woven textile from Akwete town in Abia State, Nigeria, produced by Igbo women and known for its unique weaving techniques and complex patterns.",
                            Name = "Akwete",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8747)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8754),
                            Description = "A richly embroidered fabric from Northern Nigeria, featuring intricate hand-stitched patterns around the neckline and chest, commonly used in traditional Hausa and Fulani attire.",
                            Name = "Hausa Embroidered Fabric",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8759)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8767),
                            Description = "A coarse, hand-woven cotton fabric from Northern Nigeria traditionally produced by the Hausa people, known for its natural earthy tones and used in everyday traditional wear.",
                            Name = "Kijipa",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8772)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8780),
                            Description = "A plain hand-woven Yoruba cloth from South-Western Nigeria, typically woven in white or neutral tones and used as a base fabric for dyeing techniques like Adire.",
                            Name = "Ofi",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8785)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8793),
                            Description = "A dark navy blue hand-woven Yoruba fabric from South-Western Nigeria, traditionally reserved for elders and people of high social standing during important ceremonies.",
                            Name = "Etu",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8798)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8805),
                            Description = "A prestigious hand-woven Yoruba fabric made from the silk of the Anaphe moth, featuring a distinctive brown or beige tone and traditionally worn by Yoruba royalty.",
                            Name = "Sanyan",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8810)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8818),
                            Description = "A fine hand-woven fabric from the Yoruba people of South-Western Nigeria, known for its delicate thread work and typically worn during high-profile traditional occasions.",
                            Name = "Alabere",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8822)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8830),
                            Description = "A traditional hand-woven fabric from Okene in Kogi State, produced by the Ebira people, known for its bold geometric patterns and cultural significance in Central Nigeria.",
                            Name = "Okene Weave",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8834)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8843),
                            Description = "A traditional handwoven fabric from the Ogoja people of Cross River State, known for its earthy tones and symbolic patterns used in ceremonial and ritual contexts.",
                            Name = "Ogoja Cloth",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8848)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8855),
                            Description = "A traditional fabric from the Urhobo people of Delta State, Nigeria, featuring distinct woven patterns and used during cultural festivals and important ceremonies.",
                            Name = "Urhobo Cloth",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8860)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8868),
                            Description = "A hand-woven fabric from the Igala people of Kogi State, Nigeria, known for its colorful striped patterns and cultural importance in royal and ceremonial dressing.",
                            Name = "Igala Weave",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8873)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8878),
                            Description = "A traditional hand-woven fabric from the Tiv people of Benue State, Nigeria, distinctively featuring black and white striped patterns called Anger, used in traditional ceremonies.",
                            Name = "Tiv Cloth",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8880)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8885),
                            Description = "A traditional fabric from the Nupe people of Niger State, Nigeria, known for intricate hand-loom weaving techniques and vibrant colors used in royal ceremonial attire.",
                            Name = "Nupe Weave",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8886)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8888),
                            Description = "A traditional fabric from the Efik people of Cross River State, Nigeria, commonly used during the famous Calabar carnival and cultural ceremonies such as the Ekpe festival.",
                            Name = "Efik Cloth",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8889)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8891),
                            Description = "A traditional ceremonial fabric from the Ijaw people of the Niger Delta region, typically featuring bold colors and worn alongside coral beads during important cultural and royal events.",
                            Name = "Ijaw Wrapper",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 88, DateTimeKind.Unspecified).AddTicks(8892)
                        });
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 2, 862, DateTimeKind.Unspecified).AddTicks(757),
                            HexCode = "#000000",
                            Name = "Black",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 85, DateTimeKind.Unspecified).AddTicks(8629)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3278),
                            HexCode = "#FFFFFF",
                            Name = "White",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3308)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3320),
                            HexCode = "#FF0000",
                            Name = "Red",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3325)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3332),
                            HexCode = "#001F5B",
                            Name = "Navy Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3337)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3339),
                            HexCode = "#4169E1",
                            Name = "Royal Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3340)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3345),
                            HexCode = "#87CEEB",
                            Name = "Sky Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3349)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3356),
                            HexCode = "#008080",
                            Name = "Teal",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3357)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3360),
                            HexCode = "#40E0D0",
                            Name = "Turquoise",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3361)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3363),
                            HexCode = "#008000",
                            Name = "Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3366)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3372),
                            HexCode = "#6B8E23",
                            Name = "Olive Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3376)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3382),
                            HexCode = "#98FF98",
                            Name = "Mint Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3387)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3392),
                            HexCode = "#32CD32",
                            Name = "Lime Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3394)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3397),
                            HexCode = "#FFFF00",
                            Name = "Yellow",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3401)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3408),
                            HexCode = "#FFDB58",
                            Name = "Mustard Yellow",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3412)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3414),
                            HexCode = "#FFD700",
                            Name = "Gold",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3415)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3421),
                            HexCode = "#FF8C00",
                            Name = "Orange",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3424)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3430),
                            HexCode = "#FF6B6B",
                            Name = "Coral",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3433)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3438),
                            HexCode = "#FFCBA4",
                            Name = "Peach",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3443)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3448),
                            HexCode = "#FFC0CB",
                            Name = "Pink",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3449)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3455),
                            HexCode = "#FF69B4",
                            Name = "Hot Pink",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3458)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3466),
                            HexCode = "#FF00FF",
                            Name = "Fuchsia",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3467)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3535),
                            HexCode = "#FF0090",
                            Name = "Magenta",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3540)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3548),
                            HexCode = "#800080",
                            Name = "Purple",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3553)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3560),
                            HexCode = "#E6E6FA",
                            Name = "Lavender",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3561)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3563),
                            HexCode = "#EE82EE",
                            Name = "Violet",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3564)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3566),
                            HexCode = "#4B0082",
                            Name = "Indigo",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3568)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3570),
                            HexCode = "#800000",
                            Name = "Maroon",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3572)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3574),
                            HexCode = "#800020",
                            Name = "Burgundy",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3575)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3577),
                            HexCode = "#722F37",
                            Name = "Wine Red",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3582)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3588),
                            HexCode = "#DC143C",
                            Name = "Crimson",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3592)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3599),
                            HexCode = "#FF2400",
                            Name = "Scarlet",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3602)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3609),
                            HexCode = "#8B4513",
                            Name = "Brown",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3613)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3616),
                            HexCode = "#7B3F00",
                            Name = "Chocolate",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3617)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3619),
                            HexCode = "#C68642",
                            Name = "Caramel",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3624)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3630),
                            HexCode = "#D2B48C",
                            Name = "Tan",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3633)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3639),
                            HexCode = "#F5F5DC",
                            Name = "Beige",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3642)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3648),
                            HexCode = "#FFFDD0",
                            Name = "Cream",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3652)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3658),
                            HexCode = "#FFFFF0",
                            Name = "Ivory",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3661)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3668),
                            HexCode = "#FAF9F6",
                            Name = "Off White",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3670)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3672),
                            HexCode = "#D3D3D3",
                            Name = "Light Gray",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3674)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3678),
                            HexCode = "#808080",
                            Name = "Gray",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3681)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3687),
                            HexCode = "#404040",
                            Name = "Dark Gray",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3691)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3697),
                            HexCode = "#36454F",
                            Name = "Charcoal",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3700)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3706),
                            HexCode = "#C0C0C0",
                            Name = "Silver",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3707)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3709),
                            HexCode = "#B76E79",
                            Name = "Rose Gold",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3711)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3715),
                            HexCode = "#B87333",
                            Name = "Copper",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3719)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3725),
                            HexCode = "#CD7F32",
                            Name = "Bronze",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3729)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3735),
                            HexCode = "#C3B091",
                            Name = "Khaki",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3738)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3745),
                            HexCode = "#C2B280",
                            Name = "Sand",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3748)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3754),
                            HexCode = "#B7410E",
                            Name = "Rust",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3755)
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3758),
                            HexCode = "#FA8072",
                            Name = "Salmon",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3759)
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3764),
                            HexCode = "#DCAE96",
                            Name = "Dusty Rose",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3767)
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3812),
                            HexCode = "#DE5D83",
                            Name = "Blush",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3817)
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3825),
                            HexCode = "#89CFF0",
                            Name = "Baby Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3830)
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3838),
                            HexCode = "#B0E0E6",
                            Name = "Powder Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3839)
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3842),
                            HexCode = "#007BA7",
                            Name = "Cerulean",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3843)
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3847),
                            HexCode = "#0047AB",
                            Name = "Cobalt Blue",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3851)
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3859),
                            HexCode = "#B2AC88",
                            Name = "Sage Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3862)
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3864),
                            HexCode = "#228B22",
                            Name = "Forest Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3865)
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3867),
                            HexCode = "#50C878",
                            Name = "Emerald Green",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3870)
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3875),
                            HexCode = "#00A86B",
                            Name = "Jade",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3879)
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3886),
                            HexCode = "#C8A2C8",
                            Name = "Lilac",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3890)
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3894),
                            HexCode = "#E0B0FF",
                            Name = "Mauve",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3895)
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3897),
                            HexCode = "#DDA0DD",
                            Name = "Plum",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3899)
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3901),
                            HexCode = "#614051",
                            Name = "Eggplant",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3903)
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3905),
                            HexCode = "#FFF44F",
                            Name = "Lemon Yellow",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3906)
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3909),
                            HexCode = "#FFBF00",
                            Name = "Amber",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3910)
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3912),
                            HexCode = "#FBCEB1",
                            Name = "Apricot",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3917)
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3923),
                            HexCode = "#E2725B",
                            Name = "Terracotta",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3926)
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3934),
                            HexCode = "#CB4154",
                            Name = "Brick Red",
                            UpdatedAt = new DateTime(2026, 5, 15, 14, 24, 3, 86, DateTimeKind.Unspecified).AddTicks(3936)
                        });
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Fabric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerYard")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockYards")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColorId");

                    b.ToTable("Fabrics");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FabricId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FabricId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Conversation", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nkay_fabs_backend.Entities.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.EmailVerification", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.User", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Fabric", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.Category", "Category")
                        .WithMany("Fabrics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nkay_fabs_backend.Entities.Color", "Color")
                        .WithMany("Fabrics")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Message", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nkay_fabs_backend.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Notification", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Order", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.OrderItem", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.Fabric", "Fabric")
                        .WithMany()
                        .HasForeignKey("FabricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nkay_fabs_backend.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabric");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.OtpVerification", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.User", "User")
                        .WithMany("OtpVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Category", b =>
                {
                    b.Navigation("Fabrics");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Color", b =>
                {
                    b.Navigation("Fabrics");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.User", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("EmailVerifications");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("OtpVerifications");
                });
#pragma warning restore 612, 618
        }
    }
}
