// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace nkay_fabs_backend.Migrations
{
    [DbContext(typeof(FabricsDbContext))]
    [Migration("20260507085447_InitialDataseed")]
    partial class InitialDataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nkay_fabs_backend.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 448, DateTimeKind.Unspecified).AddTicks(8264),
                            Description = "A vibrant wax print fabric widely used across Nigeria, known for its bold, colorful patterns and commonly worn at celebrations, ceremonies and everyday occasions.",
                            Name = "Ankara",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 448, DateTimeKind.Unspecified).AddTicks(8291)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1666),
                            Description = "A hand-loomed Yoruba fabric from South-Western Nigeria, traditionally worn at weddings and ceremonies, available in three types: Oja, Ipele, and Fila.",
                            Name = "Aso-Oke",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1680)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1690),
                            Description = "A traditional Yoruba indigo-dyed fabric from Nigeria, featuring intricate tie-dye or starch-resist (eleko) patterns, originating from Abeokuta and Ibadan.",
                            Name = "Adire",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1695)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1698),
                            Description = "A luxurious fabric popular in South-Eastern Nigeria, commonly worn by Igbo and Ijaw women during weddings and special ceremonies, often adorned with glitter or embroidery.",
                            Name = "George Fabric",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1699)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1701),
                            Description = "A traditional Igbo fabric from South-Eastern Nigeria featuring lion head prints, typically worn by men of title and distinction during cultural events and ceremonies.",
                            Name = "Isiagu",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1706)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1713),
                            Description = "A hand-woven textile from Akwete town in Abia State, Nigeria, produced by Igbo women and known for its unique weaving techniques and complex patterns.",
                            Name = "Akwete",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1714)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1755),
                            Description = "A richly embroidered fabric from Northern Nigeria, featuring intricate hand-stitched patterns around the neckline and chest, commonly used in traditional Hausa and Fulani attire.",
                            Name = "Hausa Embroidered Fabric",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1756)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1761),
                            Description = "A coarse, hand-woven cotton fabric from Northern Nigeria traditionally produced by the Hausa people, known for its natural earthy tones and used in everyday traditional wear.",
                            Name = "Kijipa",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1765)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1771),
                            Description = "A plain hand-woven Yoruba cloth from South-Western Nigeria, typically woven in white or neutral tones and used as a base fabric for dyeing techniques like Adire.",
                            Name = "Ofi",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1772)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1774),
                            Description = "A dark navy blue hand-woven Yoruba fabric from South-Western Nigeria, traditionally reserved for elders and people of high social standing during important ceremonies.",
                            Name = "Etu",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1776)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1782),
                            Description = "A prestigious hand-woven Yoruba fabric made from the silk of the Anaphe moth, featuring a distinctive brown or beige tone and traditionally worn by Yoruba royalty.",
                            Name = "Sanyan",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1786)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1789),
                            Description = "A fine hand-woven fabric from the Yoruba people of South-Western Nigeria, known for its delicate thread work and typically worn during high-profile traditional occasions.",
                            Name = "Alabere",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1790)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1792),
                            Description = "A traditional hand-woven fabric from Okene in Kogi State, produced by the Ebira people, known for its bold geometric patterns and cultural significance in Central Nigeria.",
                            Name = "Okene Weave",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1796)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1804),
                            Description = "A traditional handwoven fabric from the Ogoja people of Cross River State, known for its earthy tones and symbolic patterns used in ceremonial and ritual contexts.",
                            Name = "Ogoja Cloth",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1806)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1808),
                            Description = "A traditional fabric from the Urhobo people of Delta State, Nigeria, featuring distinct woven patterns and used during cultural festivals and important ceremonies.",
                            Name = "Urhobo Cloth",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1810)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1816),
                            Description = "A hand-woven fabric from the Igala people of Kogi State, Nigeria, known for its colorful striped patterns and cultural importance in royal and ceremonial dressing.",
                            Name = "Igala Weave",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1820)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1822),
                            Description = "A traditional hand-woven fabric from the Tiv people of Benue State, Nigeria, distinctively featuring black and white striped patterns called Anger, used in traditional ceremonies.",
                            Name = "Tiv Cloth",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1824)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1828),
                            Description = "A traditional fabric from the Nupe people of Niger State, Nigeria, known for intricate hand-loom weaving techniques and vibrant colors used in royal ceremonial attire.",
                            Name = "Nupe Weave",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1830)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1837),
                            Description = "A traditional fabric from the Efik people of Cross River State, Nigeria, commonly used during the famous Calabar carnival and cultural ceremonies such as the Ekpe festival.",
                            Name = "Efik Cloth",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1839)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1841),
                            Description = "A traditional ceremonial fabric from the Ijaw people of the Niger Delta region, typically featuring bold colors and worn alongside coral beads during important cultural and royal events.",
                            Name = "Ijaw Wrapper",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 449, DateTimeKind.Unspecified).AddTicks(1842)
                        });
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 251, DateTimeKind.Unspecified).AddTicks(6400),
                            HexCode = "#000000",
                            Name = "Black",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(1748)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5136),
                            HexCode = "#FFFFFF",
                            Name = "White",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5153)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5167),
                            HexCode = "#FF0000",
                            Name = "Red",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5172)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5180),
                            HexCode = "#001F5B",
                            Name = "Navy Blue",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5181)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5185),
                            HexCode = "#4169E1",
                            Name = "Royal Blue",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5189)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5197),
                            HexCode = "#87CEEB",
                            Name = "Sky Blue",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5198)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5200),
                            HexCode = "#008080",
                            Name = "Teal",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5201)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5203),
                            HexCode = "#40E0D0",
                            Name = "Turquoise",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5204)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5208),
                            HexCode = "#008000",
                            Name = "Green",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5211)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5219),
                            HexCode = "#6B8E23",
                            Name = "Olive Green",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5220)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5223),
                            HexCode = "#98FF98",
                            Name = "Mint Green",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5224)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5226),
                            HexCode = "#32CD32",
                            Name = "Lime Green",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5227)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5230),
                            HexCode = "#FFFF00",
                            Name = "Yellow",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5230)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5233),
                            HexCode = "#FFDB58",
                            Name = "Mustard Yellow",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5234)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5237),
                            HexCode = "#FFD700",
                            Name = "Gold",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5238)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5240),
                            HexCode = "#FF8C00",
                            Name = "Orange",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5241)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5248),
                            HexCode = "#FF6B6B",
                            Name = "Coral",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5250)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5284),
                            HexCode = "#FFCBA4",
                            Name = "Peach",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5286)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5288),
                            HexCode = "#FFC0CB",
                            Name = "Pink",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5289)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5293),
                            HexCode = "#FF69B4",
                            Name = "Hot Pink",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5297)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5305),
                            HexCode = "#FF00FF",
                            Name = "Fuchsia",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5306)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5352),
                            HexCode = "#FF0090",
                            Name = "Magenta",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5359)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5367),
                            HexCode = "#800080",
                            Name = "Purple",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5368)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5370),
                            HexCode = "#E6E6FA",
                            Name = "Lavender",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5371)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5374),
                            HexCode = "#EE82EE",
                            Name = "Violet",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5375)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5378),
                            HexCode = "#4B0082",
                            Name = "Indigo",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5380)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5383),
                            HexCode = "#800000",
                            Name = "Maroon",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5384)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5387),
                            HexCode = "#800020",
                            Name = "Burgundy",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5388)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5391),
                            HexCode = "#722F37",
                            Name = "Wine Red",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5392)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5395),
                            HexCode = "#DC143C",
                            Name = "Crimson",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5396)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5399),
                            HexCode = "#FF2400",
                            Name = "Scarlet",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5400)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5403),
                            HexCode = "#8B4513",
                            Name = "Brown",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5404)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5407),
                            HexCode = "#7B3F00",
                            Name = "Chocolate",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5409)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5411),
                            HexCode = "#C68642",
                            Name = "Caramel",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5412)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5415),
                            HexCode = "#D2B48C",
                            Name = "Tan",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5416)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5419),
                            HexCode = "#F5F5DC",
                            Name = "Beige",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5421)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5423),
                            HexCode = "#FFFDD0",
                            Name = "Cream",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5425)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5428),
                            HexCode = "#FFFFF0",
                            Name = "Ivory",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5429)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5432),
                            HexCode = "#FAF9F6",
                            Name = "Off White",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5433)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5436),
                            HexCode = "#D3D3D3",
                            Name = "Light Gray",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5437)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5440),
                            HexCode = "#808080",
                            Name = "Gray",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5442)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5444),
                            HexCode = "#404040",
                            Name = "Dark Gray",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5446)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5448),
                            HexCode = "#36454F",
                            Name = "Charcoal",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5450)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5453),
                            HexCode = "#C0C0C0",
                            Name = "Silver",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5454)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5457),
                            HexCode = "#B76E79",
                            Name = "Rose Gold",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5459)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5461),
                            HexCode = "#B87333",
                            Name = "Copper",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5463)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5465),
                            HexCode = "#CD7F32",
                            Name = "Bronze",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5467)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5469),
                            HexCode = "#C3B091",
                            Name = "Khaki",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5470)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5473),
                            HexCode = "#C2B280",
                            Name = "Sand",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5474)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5477),
                            HexCode = "#B7410E",
                            Name = "Rust",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5481)
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5488),
                            HexCode = "#FA8072",
                            Name = "Salmon",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5489)
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5491),
                            HexCode = "#DCAE96",
                            Name = "Dusty Rose",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5493)
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5526),
                            HexCode = "#DE5D83",
                            Name = "Blush",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5528)
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5531),
                            HexCode = "#89CFF0",
                            Name = "Baby Blue",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5532)
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5534),
                            HexCode = "#B0E0E6",
                            Name = "Powder Blue",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5535)
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5537),
                            HexCode = "#007BA7",
                            Name = "Cerulean",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5538)
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5541),
                            HexCode = "#0047AB",
                            Name = "Cobalt Blue",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5543)
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5545),
                            HexCode = "#B2AC88",
                            Name = "Sage Green",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5547)
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5550),
                            HexCode = "#228B22",
                            Name = "Forest Green",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5551)
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5554),
                            HexCode = "#50C878",
                            Name = "Emerald Green",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5555)
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5558),
                            HexCode = "#00A86B",
                            Name = "Jade",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5559)
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5562),
                            HexCode = "#C8A2C8",
                            Name = "Lilac",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5564)
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5566),
                            HexCode = "#E0B0FF",
                            Name = "Mauve",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5568)
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5570),
                            HexCode = "#DDA0DD",
                            Name = "Plum",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5572)
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5574),
                            HexCode = "#614051",
                            Name = "Eggplant",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5576)
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5578),
                            HexCode = "#FFF44F",
                            Name = "Lemon Yellow",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5580)
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5582),
                            HexCode = "#FFBF00",
                            Name = "Amber",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5584)
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5586),
                            HexCode = "#FBCEB1",
                            Name = "Apricot",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5588)
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5591),
                            HexCode = "#E2725B",
                            Name = "Terracotta",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5592)
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5595),
                            HexCode = "#CB4154",
                            Name = "Brick Red",
                            UpdatedAt = new DateTime(2026, 5, 7, 9, 54, 44, 446, DateTimeKind.Unspecified).AddTicks(5596)
                        });
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Fabric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerYard")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockYards")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColorId");

                    b.ToTable("Fabrics");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Fabric", b =>
                {
                    b.HasOne("nkay_fabs_backend.Entities.Category", "Category")
                        .WithMany("Fabrics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nkay_fabs_backend.Entities.Color", "Color")
                        .WithMany("Fabrics")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Category", b =>
                {
                    b.Navigation("Fabrics");
                });

            modelBuilder.Entity("nkay_fabs_backend.Entities.Color", b =>
                {
                    b.Navigation("Fabrics");
                });
#pragma warning restore 612, 618
        }
    }
}
